### ISSUE TITLE
@published issue

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/sage-directives#10]
Sorry, now seems to be throwing up another error:

`<time class="entry-time">
  <span>@published('F j, Y')</span>
  <span itemprop="datePublished" content="@published('c')"></span>
</time>`
![screenshot 2019-02-12 at 23 04 37](https://user-images.githubusercontent.com/18347097/52674145-9fe8cc80-2f1a-11e9-9af3-1c49ccf40271.png)

**Comment by Log1x** [comment]
Pushed a fix for v1.0.5. Sorry about that!
