### ISSUE TITLE
How to use blade loop variable?

### ISSUE THREAD

**Issue by jopfre** [Log1x/sage-directives#119]
It says in the docs it should be available in @posts

I get `Warning : Undefined variable $loop`

I am trying to use it like

```
@posts
     @if ($loop->even)
          <div id="1">
     @else
          <div id="2">
     @endif
 @endposts
 ```

Am I doing something wrong?

**Comment by Log1x** [comment]
are you on v2.0.2?

**Comment by jopfre** [comment]
Ah no sorry. Can't update now but will look into it soon. Thank you
