### ISSUE TITLE
[Question] How to get thumbnails from an image

### ISSUE THREAD

**Issue by Jimmylet** [Log1x/sage-directives#12]
Hello,

I'm trying to recover via `@sub` and `@field` a custom size for an image but I can not do it.

`@sub('slider_image', 'sizes', 'medium')`

Can we do it?

Thank you

**Comment by Log1x** [comment]
Currently isn't possible– but I can add it.  I have a beta branch right now that I need to find time to double check over and then I'll add this and push it. It will work the example above.

Sorry for the delay.
