### ISSUE TITLE
Incorrect end directives

### ISSUE THREAD

**Issue by codepuncher** [Log1x/sage-directives#13]
In the docs, some of the end directives are incorrect and causes PHP errors like
```
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected 'endif' (T_ENDIF)
```

```blade
@hasfield('list')
  <ul>
    @fields('list')
      <li>@sub('item')</li>
    @fields
  </ul>
@endfield
```

Should be

```blade
@hasfield('list')
  <ul>
    @fields('list')
      <li>@sub('item')</li>
    @endfields
  </ul>
@endfield
```

Took me an embarrassing amount of time to realise why the directives weren't working.

**Comment by Log1x** [comment]
Haha sorry. I'm pushing a new version soon and I'll take a look through the docs and see if I can't spot any other typos.
