### ISSUE TITLE
ACF Directives Not Rendering

### ISSUE THREAD

**Issue by devotoare** [Log1x/sage-directives#14]
I can't seem to get the ACF directives working?

My code:
```
@layouts('page_builder')
  {{{ get_the_title() }}}
@endlayouts
```

Renders:
<img width="370" alt="Screen Shot 2019-04-10 at 9 48 29 AM" src="https://user-images.githubusercontent.com/5583396/55897681-d1c28c00-5b75-11e9-956d-692fc657665e.png">

Other directives work fine.

**Comment by devotoare** [comment]
Figured it out, I was including ACF as part of my theme and it was not being loaded into the WordPress plugin list. I changed it to an MU Plugin and now the ACF directives work.

**Comment by yCodeTech** [comment]
> Figured it out, I was including ACF as part of my theme and it was not being loaded into the WordPress plugin list. I changed it to an MU Plugin and now the ACF directives work.

This should be part of the documentation. I couldn't get the directives to work. But as soon as I changed the ACF plugin to an MU plugin it works. There needs to be documentation addressing this.
