### ISSUE TITLE
`@style` is already in use in Laravel Blade 

### ISSUE THREAD

**Issue by maximilliangeorge** [Log1x/sage-directives#142]
I was scratching my head for quite a few minutes until I realised what was going on.

I tried to apply conditional style rules to an element using `@style` as per the [Laravel Blade docs.](https://laravel.com/docs/10.x/blade#conditional-classes)

```
<div class="flex" @style([
  'align-items: center' => $align === 'center'
])>
```

The above code rendered:

```
<div class="flex" <link="" rel="stylesheet" href="[
  align-items: center => $align === center
]">
```

Turns out it was this packages that added its own `@style` directive to overwrite the default. Perhaps another name can be used, like `@stylesheet`.

**Comment by Log1x** [comment]
`@stylesheet` sounds good. Care to do a PR?
