### ISSUE TITLE
Followed the docs but I get 'Command "docs:build" not found'

### ISSUE THREAD

**Issue by moisreis** [Log1x/sage-directives#143]
I installed it in the Sage directory **(/themes/sage)** using composer in the local machine with 'vagrant ssh' and it worked; I then ran **'yarn install'** in the themes and after themes I ran **'yarn run docs:build'** but it returned an error:

lili@Tito:~/Projetos/minhajacobina.com/site/web/app/themes/sandbox$ yarn run docs:build
yarn run v1.22.19
error Command "docs:build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Log1x** [comment]
Hi! 

Those instructions are just for building the documentation at https://log1x.github.io/sage-directives-docs/ – you wouldn't use that in your theme.

**Comment by moisreis** [comment]
I see! Can you help? I really need your amazing package to work! Where did I go wrong? Do you have any other links that could be of assistance? Thanks a lot!

**Comment by Log1x** [comment]
What problems are you having? If you installed it with Composer, it should be ready to roll.

If it's not working, try running `wp acorn optimize:clear`

**Comment by moisreis** [comment]
I ran **wp acorn optimize:clear** and its working now. Thanks you!!!!!
