### ISSUE TITLE
Add the ability to pass arrays to Directives

### ISSUE THREAD

**Issue by Log1x** [Log1x/sage-directives#16]
Right now, since Blade casts anything passed to a directive as a string, everything currently passes through [`Util::parse()`](https://github.com/Log1x/sage-directives/blob/master/src/Utilities.php#L13) to explode the parameters it into a collection allowing the use of `$expression->get(0)`, `$expression->get(1)`, etc. which I more or less find to be the cleanest approach outside of using `list() = explode()`.

Ideally, I'd like to figure out a way (regex?) to cast parameters passed as a short-handed array to an array without the current implementation of `parse()` breaking it due to exploding the colons.

Looking around online, it appears a common approach is to pass the expression through `eval()`, but for obvious reasons I am in no way interested in doing that.

If anybody has any ideas or would like to take a stab at this, it'd be greatly appreciated. It would help a lot in extending the usability/possibilities of various directives with them having so many parameters.

**Comment by rku4er** [comment]
Why don't encode input array into json and then decode it in a Blade directive?

**Comment by Log1x** [comment]
It's not so much the array its self, it's handling the comma's for breaking up the arguments passed to the directives before the `explode()`. Ideally I'd like to keep the `explode()` in place one way or another and continue using `collect()->get()` for the arguments as I'm currently doing.

Perhaps `preg_split()`? Although I'm not very great with Regex.

**Comment by rku4er** [comment]
Oh, I see. Yes, preg_slit() is good but you may need to split the key=>value pairs afterwards. I can suggest to use preg_match_all. Also look at this tool - [phpliveregex](https://www.phpliveregex.com/#tab-preg-split) for testing such things.
For example: 
```
preg_match_all('/(["\'a-zA-Z0-9_-]+)(?: => )?(["\'a-zA-Z0-9_-]+)?(?:,\s)?/', $input_lines, $output_array);
```
This function above could break such string like `"param1, param2 => "value2", param3 => 123"` into a handy data array:
```
array(3
  0 ->  array(3
    0 ->  param1,
    1 ->  param2 => "value2",
    2 ->  param3 => 123
  ),
  1 ->  array(3
    0 ->  param1
    1 ->  param2
    2 ->  param3
  ),
  2 ->  array(3
    0 ->  
    1 ->  "value2"
    2 ->  123
  )
)
```
So you have access to all params(array[1]) and values(array[1]) in a order they appear in an input string. But not sure how to be if there is comma in the value string.
