### ISSUE TITLE
Using a !not directive

### ISSUE THREAD

**Issue by raymondkingston** [Log1x/sage-directives#18]
`@if (have_posts())` becomes `@posts`
Love it.

Roots Sage's 404 uses `@if ( ! have_posts())`
Is there a ! not directive equivalent ?

[btw, great job with this project. thanks.]

**Comment by Log1x** [comment]
Having a hard time thinking on how to sanely implement that at the moment although I've thought about it in the past.

In cases where I've actually needed conditionals on my queries, I've always handled them myself within a Controller.
