### ISSUE TITLE
Undefined function 

### ISSUE THREAD

**Issue by kevin-demand** [Log1x/sage-directives#2]
/current/vendor/log1x/sage-directives/src/Directives.php

Know why I'd be getting undefined function error  Call to undefined function App\Directives\collect() on line 36 ?

````php
 public function __construct()
    {
        /**
         * Collect Directives into a flattened array.
         */
        $directives = collect($this->directives)
            ->flatMap(function ($directive) {
               if ($directive === 'ACF' && !function_exists('acf')) {
                    return;
                }
                return $this->get($directive);
            });
````

**Comment by Log1x** [comment]
Perhaps it's initializing before Sage. `collect()` is included with Sage 9 as part of illuminate/support.

What happens if you manually change [L73](https://github.com/Log1x/sage-directives/blob/master/src/Directives.php#L73) of Directives.php to:

```php
add_action('after_setup_theme', function () {
    new Directives();
});
```

**Comment by kevin-demand** [comment]
> Perhaps it's initializing before Sage. `collect()` is included with Sage 9 as part of illuminate/support.
> 
> What happens if you manually change [L73](https://github.com/Log1x/sage-directives/blob/master/src/Directives.php#L73) of Directives.php to:
> 
> ```
> add_action('after_setup_theme', function () {
>     new Directives();
> });
> ```

Must be a long day, I realized that I was requiring it on "site" not in the Sage directory when I couldn't find L73 directory. Thanks for your help!
