### ISSUE TITLE
Get index @fields

### ISSUE THREAD

**Issue by huubl** [Log1x/sage-directives#22]
Hi,

Is it possible to get the index of the loop with `@fields`? Something like:

```
<ul>
  @fields('list')
    <li>@sub('item') - @index </li>
  @endfields
</ul>
```

**Comment by Log1x** [comment]
This should work I believe:

```
<ul>
  @set($index = 1)
  @fields('list')
    <li>@sub('item') - {{ $index }}</li>
    @set($index++)
  @endfields
</ul>
```

**Comment by QWp6t** [comment]
@Log1x If you're interested, you can check out the CompilesLoops trait in illuminate/view, you'll see how the [`$loop` variable](https://laravel.com/docs/5.8/blade#the-loop-variable) is created, and how to add your loop to the stack to make the variable available via your custom directive.

**Comment by Log1x** [comment]
I actually tried to look around for where `$loop` was coming from at one point but didn't get far- I will take a look at that and implement it.

Take a look [here](https://github.com/Log1x/sage-directives/blob/master/src/Directives/Helpers.php#L174-L194) for a related giggle. 😏

**Comment by QWp6t** [comment]
You can also use the [`if` helper method to quickly whip up custom conditional statements](https://laravel.com/docs/5.8/blade#custom-if-statements). I saw that you have a few of them, so figured you might be interested.

Here's an example of some that I use.

![image](https://user-images.githubusercontent.com/2104321/66972605-f67a4d80-f049-11e9-807e-52e41675d9ff.png)

**Comment by huubl** [comment]
> This should work I believe:
> 
> ```
> <ul>
>   @set($index = 1)
>   @fields('list')
>     <li>@sub('item') - {{ $index }}</li>
>     @set($index++)
>   @endfields
> </ul>
> ```

Thanks!
