### ISSUE TITLE
@field with Images can't declare size

### ISSUE THREAD

**Issue by kupoback** [Log1x/sage-directives#24]
When using the `@field` with an array image, as the third parameter is the ID, I didn't see anywhere in the documentation on how to declare `sizes` and `image_size` within the directive. Was there something I'm missing, or something not understood?

**Comment by Log1x** [comment]
How about [@image](https://log1x.github.io/sage-directives-docs/usage/wordpress.html#image)?

**Comment by kupoback** [comment]
Didn't see that in the docs at all, i'll dig through the code and see what the params are

**Comment by kupoback** [comment]
Ah, it's part of the WP portion of it. You have to hardcode the alt tag tho?

EDIT2: This works, but not exactly ideal as the `@image` still hardcodes in the `width` and `height`. Thanks

**Comment by Log1x** [comment]
Does it still hardcode `width`/`height` with `full` passed as the second param? 

https://developer.wordpress.org/reference/functions/wp_get_attachment_image/

The directive is more or less the above with some magic for getting the image ID (e.g. ACF fields, etc.) and no `$icon` param.

**Comment by kupoback** [comment]
@Log1x Yes it does `@image('field_name', 'full')` returns the following, I cut out the url's.
`<img width="2200" height="1387" src="{url}" class="attachment-full size-full" alt="" srcset="{srcset_urls}" sizes="(max-width: 2200px) 100vw, 2200px">`

**Comment by Log1x** [comment]
Gotcha.

`width` and `height` aren't actually being set, but being set by the browser from the srcset/sizes which seemingly can't be unset due to https://core.trac.wordpress.org/browser/tags/5.2/src/wp-includes/media.php#L891

It looks like the best option might be to do something where if the second param is something like `raw`, it will use a different method for returning the image.

**Comment by kupoback** [comment]
Would it be a duplication or a pain to create a `@fieldimage('field', ['param'], 'id')` incase someone actually gets full use out of the `@image()` directive?

**Comment by Log1x** [comment]
I'm publishing a release now that allows you to pass `raw` as a second parameter to return a URL instead of an `<img>`. That seems like the best case-scenario with [this ticket](https://core.trac.wordpress.org/ticket/14110) being set as `wont fix`.
