### ISSUE TITLE
updating to accomodate laravel/helpers 

### ISSUE THREAD

**Issue by timalbert** [Log1x/sage-directives#26]
Just noticed a minor update is needed to accommodate acorn pulling in the latest from Illuminate. Not sure if you have a preference for implementing or if the plan is to pull in laravel/helpers through acorn.

Thanks again for the great resources!

**Comment by Log1x** [comment]
Hi. Not sure what you mean entirely? `laravel/helpers` shouldn't be needed as far as I know. I think I'm using `Illuminate\Support\Arr` and `Illuminate\Support\Str` everywhere as-needed.

Could you elaborate? Sorry for the confusion.

**Comment by timalbert** [comment]
Sure thing - when I updated to the latest Sage 10/Acorn I started getting this error

`Call to undefined function Log1x\SageDirectives\str_contains()`

After looking a little closer, it looks like `Illuminate\Support\Str` is just missing from the ACF.php and Helpers.php files.

**Comment by Log1x** [comment]
Ah, I did a search for `str_` but for some reason nothing came up. :) I'll push a fix.
