### ISSUE TITLE
get sub fields (related items) of item in repeater field

### ISSUE THREAD

**Issue by jmp909** [Log1x/sage-directives#3]
Hi, 

is there any way to get  sub fields (related items) of items in a repeater field 

* Custom Post Type `Foo` has a repeater field `bar_repeater`. 
* each repeated item has a field called 'title' and a Relationship called `bars`
* each relationship has one or more related Bar (Custom Post Type) items

this equivalent blade/php for instance might be

```php  
@php $bar_repeater = get_field('bar_repeater'); @endphp  
  @foreach($bar_repeater as $bar_repeater_item)
  	<h2>BAR REPEATER ITEM: {{ $bar_repeater_item['title'] }}</h2>
  	<h3>BARS</h3>
  	@foreach($bar_repeater_item['bars'] as $bar)
  		bar: {{ $bar->post_title }}<br />
  	@endforeach
  <hr />
  @endforeach
```

this doesn't work.. it shows the correct number of items but the `@sub('post_title')` is empty for the related object, but then i guess it's not actually a sub field.

 ```blade
@fields('bar_repeater')
    <h2>BAR REPEATER ITEM: @sub('title')</h2>
    <h3>Bars</h3>
    @fields('bars')
        bar: @sub('post_title')<br />
    @endfields
    <hr />
@endfields
```

thanks
J

**Comment by Log1x** [comment]
Yeah, I assume everything but `@sub('post_title')` is working in your example. This is more-so an edge-case and I can't really think of a sane way to approach it with directives. I'd personally either use [ACF Fluent](https://github.com/samrap/acf-fluent) or put it in a Controller (or both).

You can of course, use normal ACF functions, I just personally prefer ACF Fluent.

I'm going to close this for now, but if you have any ideas on how to handle it in a way that isn't excessively messy or want to submit a PR, feel free.
