### ISSUE TITLE
Post Class

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/sage-directives#31]
Can't see directive for 'post_class()'? eg.

```
<article <?php post_class() ?>>
```

There seems to be one for body_class() though. Just wondering am I missing it? 

Thanks.

**Comment by Log1x** [comment]
It doesn't exist. I'm not HUGE on the `@bodyclass` directive as-is– but seeing as it's already here, I'll add `@postclass` too when I get a chance.

**Comment by fabianwurk** [comment]
Thats great, thanks.

**Comment by fabianwurk** [comment]
Is this correct directive:

`    'postclass' => function ($expression) {
        return "<?php post_class({$expression}); ?>";
    },`

**Comment by Log1x** [comment]
yeah thats more or less it + adding reference in the docs
