### ISSUE TITLE
Missing PHP closing tag in @hasposts directive

### ISSUE THREAD

**Issue by ethicka** [Log1x/sage-directives#34]
I get the following error when using `@hasposts` and `@endhasposts` with a passed query e.g. `@hasposts($query)`.

```
Uncaught Exception: syntax error, unexpected '<', expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)
```
It appears there's a missing closing tag on the following line:

https://github.com/Log1x/sage-directives/blob/433f3a499d6414783e34b9304ba76ec4d20a38eb/src/Directives/WordPress.php#L91

When I directly edited the cached file I added `?>` to the end of the line to fix the issue.

**Comment by Log1x** [comment]
indeed a bug. care to do a PR?
