### ISSUE TITLE
Fatal error: @image($id, 'size') causing syntax error from trailing parameter comma.

### ISSUE THREAD

**Issue by christianmagill** [Log1x/sage-directives#40]
When I use the @image directive like such...

`@image($image, $image_size)`

It generates the following code...

```
    <?php echo wp_get_attachment_image(
                $image,
                $image_size,
                false,
              
            ); ?>
```

This causes a fatal error on my server due to the trailing comma:

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected ')'`

**Comment by Log1x** [comment]
Yeah, that requires PHP 7.2 if I recall. My mistake.

Care to do a PR?

**Comment by christianmagill** [comment]
I don't have much experience with creating directives, but I'll take a look.

**Comment by christianmagill** [comment]
I ended up just upping my PHP version to fix the issue.
