### ISSUE TITLE
Parsing the PHP

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/sage-directives#41]
Having an issue where the PHP isn't parsing for the Directives. 

I've installed it via composer, and it exists in the vendor folder okay. I've tried composer update. But issue still persists. Any idea why this might happen, and how to resolve?

Thanks.

<img width="1258" alt="Screenshot 2020-06-11 at 01 01 20" src="https://user-images.githubusercontent.com/18347097/84330416-39f86d80-ab7f-11ea-834d-0bf55b5860d5.png">

**Comment by Log1x** [comment]
Did you resolve this? It usually comes down to clearing the view cache.

**Comment by fabianwurk** [comment]
No, sorry I didn't - I just ended up removing all the directives and replacing with the standard ACF fields.

**Comment by fabianwurk** [comment]
Is there a way to clear the view cache?

**Comment by Log1x** [comment]
For Sage 9 I think you can just `yarn clean` or try regenerating the views manually with https://github.com/alwaysblank/blade-generate

The only other thing it could be is https://github.com/Log1x/sage-directives/blob/master/src/Directives.php#L59-L61

**Comment by fabianwurk** [comment]
I will defo give that a try, the directives are great, and way more manageable than standard ACF PHP. Thanks

**Comment by fabianwurk** [comment]
Just an update on this, I tried methods you suggested above, but these didn't resolve it. So, just had to manually remove all the cache items within the 'uploads' folder.

**Comment by thatONEjustin** [comment]
having the same problem, but clearing the cache items in uploads didn't work either.

**Comment by fabianwurk** [comment]
@thatONEjustin have you tried doing a:

`composer update`
