### ISSUE TITLE
@hasfield compiled incorrectly

### ISSUE THREAD

**Issue by DaveFlynn** [Log1x/sage-directives#44]
Got a weird issue in Sage 10 with ``@hasfield`` not compiling correctly:

This:

```php
@hasfield('menu_section', $menu_id )
    <ul>
        @fields('menu_section', $menu_id)
            <li>
                @sub('section_title')
            </li>
        @endfields
    </ul>
@endfield
```

Renders to this:

```php
<?php if (get_field('menu_section')[$menu_id]) : ?>
    <ul>
        <?php if (have_rows('menu_section', $menu_id)) : ?><?php while (have_rows('menu_section', $menu_id)) : the_row(); ?>
            <li>
                <?= get_sub_field('section_title'); ?>
            </li>
        <?php endwhile; endif; ?>
    </ul>
<?php endif; ?>
```

For some reason ``@hasfield`` renders as ``get_field('menu_section')[$menu_id]`` instead of ``get_field('menu_section', $menu_id)`` and doesn't work. If I remove the ``@hasfield`` and ``@endfield`` the code works find and displays the list of section titles.

I've reverted to ACF code for now as a workaround:

```php
<?php if (get_field('menu_section', $menu_id ) ) : ?>
    <ul>
        @fields('menu_section', $menu_id)
            <li>
                @sub('section_title')
            </li>
        @endfields
    </ul>
<?php endif; ?>

```

**Comment by EHLOVader** [comment]
@DaveFlynn do you know if https://github.com/Log1x/sage-directives/pull/68 fixes your issue? 

Can be tested with [composer patches](https://github.com/cweagans/composer-patches)
