### ISSUE TITLE
@posts should provide Blade's magic $loop variable

### ISSUE THREAD

**Issue by markjaquith** [Log1x/sage-directives#48]
It would be great if you could use [Blade's magic `$loop` variable](https://laravel.com/docs/7.x/blade#the-loop-variable) within `@posts` blocks.

For reference: https://github.com/laravel/framework/blob/7.x/src/Illuminate/View/Concerns/ManagesLoops.php

**Comment by Log1x** [comment]
I need to do this with `@repeat` as well

**Comment by jopfre** [comment]
Is it possible to show an example of how to use this?

I get `Warning : Undefined variable $loop`

I am trying to use it like

```
@posts
     @if ($loop->even)
          <div id="1">
     @else
          <div id="2">
     @endif
 @endposts
 ```
