### ISSUE TITLE
Suggestion: the_post(), setup_postdata(), wp_reset_postdata() directives.

### ISSUE THREAD

**Issue by dawidurbanski** [Log1x/sage-directives#5]
Hi. Great library!

It would be cool if you could add `the_post()` as a blade directive, like `@post` or `@thepost`.

so this default Sage template code:

```
@while(have_posts()) @php the_post() @endphp
  @include('partials.page-header')
  @include('partials.content-page')
@endwhile
```

Becomes:

```
@while(have_posts()) @thepost
  @include('partials.page-header')
  @include('partials.content-page')
@endwhile
```

It could be also useful to add directives for `setup_postdata()` and `wp_reset_postdata()`.

It would help to avoid writing boilerplate code in controllers to pass custom queries results.
For example (as you already have `@global()`):

```
@global($post)
@foreach($passed_posts as $post)
    @setuppostdata($post)
    <h1>@title</h1>
    @content
@endforeach
@resetpostdata
```

Thanks!

EDIT: never mind, i just found out that my first example makes no sense as `@posts` does exactly this.
And second one is equivalent to `@posts($passed_query) ... @endposts`

**Comment by Log1x** [comment]
🤗

**Comment by dawidurbanski** [comment]
@Log1x I decided to reopen this because I actually found a proper use case for my second example.

It's because we don't always have WP_Query instance, but sometimes an array of objects.

For example if in controller I'm gonna pass returned data from `wp_get_recent_posts()` (for example), it will contain an array of WP_Post objects instead of WP_Query object, so `@posts` won't work in such case.

The same goes if we will think about an ACF relation field. We can set field to accept multiple posts (or pages, or custom posts), and it will return an array of objects (or ID's), so in such case `@posts` does not help as well.

I know i could simply iterate over an array and echo object properties, but it's far better to use template tags to keep all applied filters.

Additionally if I'm doing mix of an array and WP_Query as a fallback, I can use the same template for this purpose.

Just to demonstrate.

```blade
--- custom-page.blade.php

@hasfield('related-posts')
    // Use posts specified in ACF related-posts field
    @global($post)
    @fields('related-posts')
        @set($post, @sub('post')) // not sure if we can nest directives
        @setuppostdata($post)
        @include(post-content.blade.php)
    @endfields
    @resetpostdata
@else // not sure if else is here allowed at all
    // use default WP_Query passed from controller
    @posts($query)
        @include(post-content.blade.php) // using the same template!
    @endposts
@endfield
```

```blade
--- post-content.blade.php

<div class="post">
    <h1>@title</h1>
    @content
</div>
```

Not sure if this makes sense, but let me know if I'm missing something.

**Comment by Log1x** [comment]
So to answer the questions from your comments:

- We can't nest directives. It's not possible with Blade.
- the `@else` is valid.

That being said, how would you vision this being marked up / handled? I can add something like `@setuppostdata` (perhaps `@postdata` would be cleaner if not confusing?) as well as `@resetpostdata` no problem- I'm just not sure the best way to handle the other things mentioned for the use-case.

Speaking on `@posts`, I should be able to check if it's an `instanceof WP_Query` when an expression is passed to it and if not, fall back to `WP_Posts` (or the other way around, doesn't really matter).

You can see [here](https://github.com/Log1x/sage-directives/blob/master/src/Directives/WordPress.php#L22) how it's being handled. The main thing is we can't actually write any conditionals like my `instanceof WP_Query` above directly in the Blade, it has to echo them out instead as Blade simply parses everything after the fact; it doesn't actually have access to anything outside of its self.

Edit: We can also handle the `global $post` in the `@postdata` directive but make it optional to pass your own variable as well.

**Comment by dawidurbanski** [comment]
I made a pull request #6 and added some comments there. If you could look at it in free time it would be great.

Thanks.

**Comment by Log1x** [comment]
Added in #6
