### ISSUE TITLE
Randomly Stopped Working, no Error Messages

### ISSUE THREAD

**Issue by thatONEjustin** [Log1x/sage-directives#61]
As the title says, the library stopped working between now and May 5th 2021. 

No changes were made to the code declaring the directives. No changes were made to the wordpress database where the data lies. 

I'm getting no errors and can confirm that the plugin is loaded in all envrionments.

**Comment by thatONEjustin** [comment]
The only thing I can get is that every field in ACF returns as null.

**Comment by thatONEjustin** [comment]
seems to be the issue lies with ACF and not the directives

**Comment by Kebie** [comment]
Do you have a fix for this you can link? or where did you see the fix at ACF? I am having this error as well.

**Comment by thatONEjustin** [comment]
> Do you have a fix for this you can link? or where did you see the fix at ACF? I am having this error as well.

Unfortunately this had to do more with a configuration issue with a Laravel Blade template not properly associating the ACF field group with the page it was intended for.
