### ISSUE TITLE
@hasfield render argument in wrong place

### ISSUE THREAD

**Issue by aitormendez** [Log1x/sage-directives#63]
`@hasfield('my_field', 113)`

render as

`<?php if (get_field('my_field')[113]) : ?>`

instead

`<?php if (get_field('my_field', 113)) : ?>`

![Captura de pantalla 2021-08-07 a las 18 42 19](https://user-images.githubusercontent.com/2788577/128607579-80551b2b-1442-4263-bc94-facaf86965f9.png)

**Comment by EHLOVader** [comment]
@aitormendez do you know if https://github.com/Log1x/sage-directives/pull/68 fixes your issue? 

Can be tested with [composer patches](https://github.com/cweagans/composer-patches)
