### ISSUE TITLE
AFC Link Array Exception Illegal string offset 'title' 

### ISSUE THREAD

**Issue by auroralabs** [Log1x/sage-directives#67]
I have set up a link as an array and output to Blade as follows:
```
<h5><a title="@sub('casino_header', 'title')" href="@sub('casino_header', 'url')">@sub('casino_header', 'title')</a></h5>
```
It generally works but when i return to the page I receive the following error
```
Illuminate \ View \ ViewException (E_ERROR)
Illegal string offset 'title' 
```
Changing it back to a standard links works ok but when i revert back to an array the same exception is thrown. This is happening randomely on other arrays including images & links. Some work some don't

Site is running version 1.2 on roots/sage 10.0.0

**Comment by Log1x** [comment]
Fixed in #82
