### ISSUE TITLE
Sage directives not working properly in Sage 9.0.9 install

### ISSUE THREAD

**Issue by dmalkin** [Log1x/sage-directives#72]
Hello,

I have Sage Directives working flawlessly in Sage 9.0.10 but I needed to downgrade to Sage 9.0.9 for a separate issue with Sage. Unfortunately, this seems to be incompatible with Sage Directives in its current 1.1 version.

I've installed it just the same as I did with all my other Sage 9.0.10 themes, but can't get it to operate.

Current Environment:
- Sage 9.0.9
- PHP 7.3.29
- Composer 2.1.5

Are there any known issues tied to Sage 9.0.9?

**Comment by Log1x** [comment]
Sage Directives 1.x should work fine for Sage 9.
