### ISSUE TITLE
Couldn't find a script named "docs:build".

### ISSUE THREAD

**Issue by RobDobsonNC** [Log1x/sage-directives#78]
Hello - setting this up on a fresh install, from within the local terminal. Install works fine, yarn build works fine. Error thrown on:

`yarn run docs:build`

Couldn't find a script named "docs:build".

Hopefully a simple workaround, but I've searched with no similar answers. Appreciate any help. Thanks!

**Comment by Log1x** [comment]
Those steps are only for building the documentation hosted at https://log1x.github.io/sage-directives-docs/ – you won't need to do that for normal usage.
