### ISSUE TITLE
Should this work with Radicle?

### ISSUE THREAD

**Issue by braco** [Log1x/sage-directives#80]
Migrated to Radicle, this doesn't seem to be working after composer install. Is that expected?

**Comment by Log1x** [comment]
https://github.com/roots/radicle/issues/14

wrap the Acorn bootloader in a `plugins_loaded` hook

**Comment by braco** [comment]
Already wrapped inside of public/content/mu-plugins/00-acorn-boot.php

```
<?php

add_filter('plugins_loaded', function () {
```

any other ideas?

**Comment by theMosaad** [comment]
> Already wrapped inside of public/content/mu-plugins/00-acorn-boot.php
> 
> ```
> <?php
> 
> add_filter('plugins_loaded', function () {
> ```
> 
> any other ideas?

It should be an `add_action` but that didn't do it for me as well.

Might this have to do with this package not having a ServiceProvider @Log1x? Happy to add one if that's the case.

**Comment by Log1x** [comment]
> It should be an `add_action` but that didn't do it for me as well.

`add_action` and `add_filter` are [the same thing](https://developer.wordpress.org/reference/functions/add_action/#source).

That aside, it does indeed need a ServiceProvider.

**Comment by theMosaad** [comment]
> `add_action` and `add_filter` are [the same thing](https://developer.wordpress.org/reference/functions/add_action/#source).

Thanks for this!

> That aside, it does indeed need a ServiceProvider.

Already patched it in Radicle and have an in-progress PR that I'll open this weekend.
