### ISSUE TITLE
@date issue

### ISSUE THREAD

**Issue by fabianwurk** [Log1x/sage-directives#9]
Tried adding this, but just echos out '@date('F j, Y')'

`<time class="entry-time">
  <span>@date('F j, Y')</span>
  <span itemprop="datePublished" content="@date('c')"></span>
</time>`
![screenshot 2019-02-12 at 22 56 08](https://user-images.githubusercontent.com/18347097/52673717-754a4400-2f19-11e9-849f-aeeb1618f8a9.png)

**Comment by Log1x** [comment]
Sorry, I typo'd it. It's supposed to be `@published` – I'll update the docs now.

**Comment by Log1x** [comment]
Fixed.

**Comment by fabianwurk** [comment]
Ah that makes sense. Thanks for updating.
